name: minitest
on: [push]
jobs:
  tests:
    name: Run Minitests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Setup rails environment
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler cyclonedx-ruby
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: |
          bin/rails db:setup
          bundle exec rake test

      - name: Generate BOM
        run: /
          cyclonedx-ruby -v --path .

      - name: Upload BOM
        env:
          DT_API_KEY: ${{ secrets.DT_API_KEY }}
          DT_API_URL: ${{ secrets.DT_API_URL }}
          DT_APPLICATION_UUID: ${{ secrets.DT_APPLICATION_UUID }}
        run: |
          curl -X "PUT" $DT_API_URL \
            -H 'Content-Type: application/json' \
            -H "X-API-Key: $(echo $DT_API_KEY)" \
            -d $"{
              "project": "$(echo $DT_APPLICATION_UUID)",
              "bom": $(base64 -w 0 bom.xml)
            }"